credentials:
- name: /concourse/infra/harbor/product-properties/server_cert
  type: certificate
  value:
    certificate: |
      <secret>
    private_key: |
      <secret>
    ca: |
      <secret>
- name: /concourse/infra/harbor/product-properties/admin_password
  type: password
  value: <secret>

  