product-name: harbor-container-registry
product-properties:
  .properties.admin_password:
    value:
      secret: ((harbor.product-properties.admin_password))
  .properties.admin_password_for_smoketest:
    value:
      secret: ((harbor.product-properties.admin_password))
  .properties.auth_mode:
    value: db_auth
  .properties.clair_updater_interval:
    value: ((harbor.product-properties.clair_updater_interval))
  .properties.customize_container_network:
    value: default
  .properties.hostname:
    value: ((harbor.product-properties.hostname))
  .properties.no_proxy:
    value: 127.0.0.1,localhost,ui,registry
  .properties.registry_storage:
    value: filesystem
  .properties.server_cert_ca:
    value: ((harbor.product-properties.server_cert_ca))
  .properties.server_cert_key:
    value: ((harbor.product-properties.server_certs))
  .properties.with_clair:
    value: true
  .properties.with_notary:
    value: true
network-properties: ((harbor.network-properties))
resource-config: ((harbor.resource-config))
errand-config: ((harbor.errand-config))


