director:
  iaas_configuration:
    iam_profile: infra_ops_manager
    key_pair_name: infra-ops-manager-key
    region: us-west-2
    security_group: sg-05d33933ea50b64d4
    ssh_private_key: |
      ((director/sshkey.private_key))

  director_configuration:
    blobstore_type: local
    database_type: internal
    ntp_servers:  0.amazon.pool.ntp.org, 1.amazon.pool.ntp.org, 2.amazon.pool.ntp.org,
      3.amazon.pool.ntp.org
    bosh_recreate_on_next_deploy: false

  security-configuration:
    generate_vm_passwords: true
    
  az-configuration:
  - name: us-west-2a
  - name: us-west-2b
  - name: us-west-2c

  network-assignment:
    network: 
      name: infrastructure
    singleton_availability_zone: 
      name: us-west-2a

  vm-extension-config:
  - name: pks-api-security-groups
    cloud_properties:
      security_groups: ["pks_api_lb_security_group", "vms_security_group"]

  networks-configuration:
    networks: 
    - name: infrastructure
      subnets:
      - iaas_identifier: subnet-050de0c7469ab2508
        cidr: 10.3.16.0/28
        dns: 10.3.0.2
        gateway: 10.3.16.1
        reserved_ip_ranges: 10.3.16.0-10.3.16.4
        availability_zone_names:
        - us-west-2a
      - iaas_identifier: subnet-05f6c80cb9a22d6e9
        cidr: 10.3.16.16/28
        dns: 10.3.0.2
        gateway: 10.3.16.17
        reserved_ip_ranges: 10.3.16.16-10.3.16.20
        availability_zone_names:
        - us-west-2b
      - iaas_identifier: subnet-048222f08e202acce
        cidr: 10.3.16.32/28
        dns: 10.3.0.2
        gateway: 10.3.16.33
        reserved_ip_ranges: 10.3.16.32-10.3.16.36
        availability_zone_names:
        - us-west-2c
    - name: pks
      subnets:
      - iaas_identifier: subnet-0ea1f7f1ffb45fdfe
        cidr: 10.3.4.0/24
        dns: 10.3.0.2
        gateway: 10.3.4.1
        reserved_ip_ranges: 10.3.4.0-10.3.4.4
        availability_zone_names:
        - us-west-2a
      - iaas_identifier: subnet-0a8ec484778e7afce
        cidr: 10.3.5.0/24
        dns: 10.3.0.2
        gateway: 10.3.5.1
        reserved_ip_ranges: 10.3.5.0-10.3.5.4
        availability_zone_names:
        - us-west-2b
      - iaas_identifier: subnet-0eb0fd26a15af9a4d
        cidr: 10.3.6.0/24
        dns: 10.3.0.2
        gateway: 10.3.6.1
        reserved_ip_ranges: 10.3.6.0-10.3.6.4
        availability_zone_names:
        - us-west-2c
    - name: services
      subnets:
      - iaas_identifier: subnet-0f8821f6265ed7313
        cidr: 10.3.8.0/24
        dns: 10.3.0.2
        gateway: 10.3.8.1
        reserved_ip_ranges: 10.3.8.0-10.3.8.4
        availability_zone_names:
        - us-west-2a
      - iaas_identifier: subnet-041fe9432710c015d
        cidr: 10.3.9.0/24
        dns: 10.3.0.2
        gateway: 10.3.9.1
        reserved_ip_ranges: 10.3.9.0-10.3.9.4
        availability_zone_names:
        - us-west-2b
      - iaas_identifier: subnet-012532d673a8f6264
        cidr: 10.3.10.0/24
        dns: 10.3.0.2
        gateway: 10.3.10.1
        reserved_ip_ranges: 10.3.10.0-10.3.10.4
        availability_zone_names:
        - us-west-2c