product-name: pivotal-container-service
product-properties:
  .pivotal-container-service.pks_tls:
    value:
      cert_pem: ((pivotal-container-service_pks_tls.cert_pem))
      private_key_pem: ((pivotal-container-service_pks_tls.private_key_pem))
  .properties.cloud_provider:
    value: AWS
  .properties.network_selector:
    value: flannel
  .properties.network_selector.flannel.pod_network_cidr:
    value: 10.200.0.0/16
  .properties.network_selector.flannel.service_cluster_cidr:
    value: 10.100.200.0/24
  .properties.pks-vrli:
    value: disabled
  .properties.pks_api_hostname:
    value: api.pks.infra.aws.warroyo.com
  .properties.plan1_selector:
    value: Plan Active
  .properties.plan2_selector:
    value: Plan Active
  .properties.plan3_selector:
    value: Plan Inactive
  .properties.proxy_selector:
    value: Disabled
  .properties.sink_resources_selector:
    value: enabled
  .properties.syslog_selector:
    value: disabled
  .properties.telemetry_selector:
    value: disabled
  .properties.uaa:
    value: internal
  .properties.uaa_oidc:
    value: false
  .properties.uaa_pks_cli_access_token_lifetime:
    value: 600
  .properties.uaa_pks_cli_refresh_token_lifetime:
    value: 21600
  .properties.vm_extensions:
    value:
    - public_ip
  .properties.wavefront:
    value: disabled
  .properties.worker_max_in_flight:
    value: 1
network-properties:
  network:
    name: infrastructure
  other_availability_zones:
  - name: us-west-2a
  - name: us-west-2b
  - name: us-west-2c
  service_network:
    name: services
  singleton_availability_zone:
    name: us-west-2a
resource-config:
  pivotal-container-service:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: true
    elb_names:
    - alb:infra-pks-tg-9021
    - alb:infra-pks-tg-8443
    additional_vm_extensions:
    - pks-api-security-groups
errand-config:
  delete-all-clusters:
    pre-delete-state: true
  pks-nsx-t-precheck:
    post-deploy-state: false
  smoke-tests:
    post-deploy-state: false
  upgrade-all-service-instances:
    post-deploy-state: true
  wavefront-alert-creation:
    post-deploy-state: false
  wavefront-alert-deletion:
    pre-delete-state: false

